apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: apr7-rag-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/apr7-rag-1:8087deb386d54d50757bd7273a6ecea1b7791841@sha256:cc43f836aa22437a7823b3e2e8cb3a17a6f673d4c2bf4486718e335efa11f2ff # use pre-built to bootstrap
          name: app-inference
